# Custom exceptions belong in this module.

class ExeggutorError(Exception):
	pass

